markdown: kramdown
permalink: pretty
relative_permalinks: false
pygments: true
paginate: 10
paginate_path: news/page:num

kramdown:
  auto_ids: false

exclude:
  - static

# Tag plugin
tag_page_layout: category
tag_page_dir: news/category

future: true
show_drafts: true
