markdown: kramdown
permalink: pretty
relative_permalinks: false
pygments: true
paginate: 10
pagination_path: news/page:num

kramdown:
  auto_ids: false

exclude:
  - static

future: true
show_drafts: true

locale:
    test:
        en: "Hello"
        de: "Hallo"
